### ISSUE TITLE
udemy.itsadarsh.tech error 404

### ISSUE THREAD

**Issue by yohanesgultom** [Adarsh-Goel/udemy-coupons-for-free#9]
The https://udemy.itsadarsh.tech is currently showing error 404. I think deletion of `CNAME` in `main` branch caused deletion in `gh-pages` as well (commited by git action). So you might want to restore it

**Comment by Adarsh-Goel** [comment]
yes true!
I have committed a fix.

**Comment by Adarsh-Goel** [comment]
seems like there is a new issue which isnt letting the script work
The error is UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 4352: invalid continuation byte

**Comment by yohanesgultom** [comment]
It seems one of the HTML page contains non-UTF-8 characters. Not sure how to actually parse them. But I've created a PR to skip the problematic page as a temporary workaround. Please help to review it

**Comment by Adarsh-Goel** [comment]
ok fine by the way are you taking part in hacktoberfest?

**Comment by yohanesgultom** [comment]
Indeed I am. And thanks to you, I've achieved the minimum PR quota 🎉
